CREATE TABLE rooms (
id INTEGER PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE students(
id INTEGER PRIMARY KEY,
name VARCHAR(100) NOT NULL,
birthday DATE NOT NULL,
sex CHAR(1) NOT NULL,
room_id INTEGER NOT NULL REFERENCES rooms(id)
);